### ISSUE TITLE
Plugin version 0.10.0 fails on Android

### ISSUE THREAD

**Issue by thedejifab** [wilburt/flutter_paystack#10]
Hi @wilburt, I tried using the plugin's new release in my Flutter Project and it keeps failing due to some reason I don't seem to understand

This is what I get on Gradle task assembleDebug

** FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not download appcompat-v7.aar (com.android.support:appcompat-v7:28.0.0)
   > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/support/appcompat-v7/28.0.0/appcompat-v7-28.0.0.aar'.
      > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/support/appcompat-v7/28.0.0/appcompat-v7-28.0.0.aar'.
         > Connect to dl.google.com:443 [dl.google.com/172.217.23.14] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Gradle task 'assembleDebug'... Done                         27.2s
Gradle task assembleDebug failed with exit code 1 **

**Comment by wilburt** [comment]
The connection is timing out. Please confirm that you have a good internet connection.

**Comment by thedejifab** [comment]
Connection is good. I just finished using it to clone the plugin project now in fact. Let me try to run the example project

**Comment by thedejifab** [comment]
> Connection is good. I just finished using it to clone the plugin project now in fact. Let me try to run the example project

The case is the same when I try to run the example project

**Comment by wilburt** [comment]
Please, can you  click this link [https://dl.google.com/dl/android/maven2/com/android/support/appcompat-v7/28.0.0/appcompat-v7-28.0.0.aar](https://dl.google.com/dl/android/maven2/com/android/support/appcompat-v7/28.0.0/appcompat-v7-28.0.0.aar) and let me know what happens?

**Comment by papakay** [comment]
I'm having similar issue on Android. The internet is very okay and was able to download the file in the link above effortlessly.

**Comment by thedejifab** [comment]
For some reasons I don't know, it now runs. I think it's a problem with dependency downloads on my end. If it persists again, I can reopen the issue
