### ISSUE TITLE
Dark Mode paystack SDK doesnt react to change

### ISSUE THREAD

**Issue by Mtconcept** [wilburt/flutter_paystack#102]
The Paystack package doesn't support the full theme mode, when i switch to dark mode it changes but the dialog box doesn't change its theme, its just white and it remains white but other items changes per the Thememode which make white lie on white in dark mode.

**Comment by DEVSOG12** [comment]
I thought #75 Fixed this.

**Comment by keezysilencer** [comment]
I am on the latest build, It is still not working.

**Comment by keezysilencer** [comment]
The best immediate solution is to wrap your widget with theme data and a Builder to get a customer context and then pass it to the checkout
`    Theme(
data: ThemeData.light(),
child: Builder(builder: (blueThemeContext) {
        return ElevatedButton(
            onPressed: () async {
              Charge charge = Charge()
                ..amount = (total * 100).toInt()
                ..reference = DateTime.now().microsecondsSinceEpoch.toString()
                ..currency = "GHS"
                ..email = "test@gmail.com";
              CheckoutResponse response = await plugin.checkout(blueThemeContext,
                  method: CheckoutMethod.card,
                  charge: charge,
                  logo: Image(image: AssetImage(Images.logo), width: 50, height: 50));
            },
            style: Theme.of(context).elevatedButtonTheme.style,
            child: Text('Confirm Booking'));
      }),
    );`

**Comment by wilburt** [comment]
This should be fixed in 1.0.6. Can you update the package version? Please, feel free to reopen this issue if the bug persists.
