### ISSUE TITLE
Migrate to Null Safety

### ISSUE THREAD

**Issue by ebukaodini** [wilburt/flutter_paystack#103]
Hi @wilburt,

Thanks for providing the community with this wonderful package. It's really helpful.

Please can you migrate the http package that your package is dependent on to null safety. It keeps throwing dependency issue when building with null-safety.

I would appreciate a response to this.

**Comment by wilburt** [comment]
Hi, can you provide the following details?

- Plugin version in your pubspec
- Error message
- Is your project migrated to null-safety?

**Comment by Adejoh-godwin** [comment]
depends on paystack_manager ^1.0.4 which depends on intl ^0.16.1, intl ^0.16.1 is required.
So, because env_zeus depends on intl ^0.17.0, version solving failed.
pub get failed (1; So, because env_zeus depends on intl ^0.17.0, version solving failed.)

I had the same issues

**Comment by Adejoh-godwin** [comment]
depends on paystack_manager ^1.0.4 which depends on intl ^0.16.1, intl ^0.16.1 is required.
So, because env_zeus depends on intl ^0.17.0, version solving failed.
pub get failed (1; So, because env_zeus depends on intl ^0.17.0, version solving failed.)

I had the same issues

**Comment by Adejoh-godwin** [comment]
Alright. Thank you
