### ISSUE TITLE
How to get accessCode

### ISSUE THREAD

**Issue by fredEbho** [wilburt/flutter_paystack#106]
Plugin doesn't work when you set accessCode

**Comment by Jereson** [comment]
Please can someone respond to this I am having issue, I don't know what the backend url contain

**Comment by toykam** [comment]
The way i works is like, you don't really need a backend server to get access code, all you need to do to get accessCode is to call the paystack transaction initialization endpoint, it will generate the accesscode and send a response. So you can either call this api from your app, or from a bakend.

**Comment by devanshdixit** [comment]
I think @toykam  has explained what does it do so this issue can be closed

**Comment by wilburt** [comment]
@toykam  provided a valid explanation. Closing this.
