### ISSUE TITLE
Unable to get metadata from webhook callback

### ISSUE THREAD

**Issue by quiet-programmer** [wilburt/flutter_paystack#107]
Hi @wilburt, I love your plugin it has helped me so far, but I'm having one issue now, the same thing from issue #72

I can't seem to get back the metadata from the response data.

here is the code

```dart

Charge charge = Charge()
      ..amount = amount * 100
      ..reference = ref
      ..email = email
      ..putMetaData('custom_feilds', [
        {
          'paymentID': '${widget.paymentId}',
        },
   ]);

```

##here is the json response
```json
"CheckoutResponse"{
   "message":"Success",
   "card":"PaymentCard"{
      "_cvc":081,
      "expiryMonth":11,
      "expiryYear":22,
      "_type":"VERVE",
      "_last4Digits":7812,
      "_number":null
   },
   "account":null,
   "reference":r974kA34nhyOnj9,
   "status":true,
   "method":"CheckoutMethod.card",
   "verify":true
}
```

**Comment by wilburt** [comment]
I sent this:
```
Charge charge = Charge()
      ..amount = 10000 // In base currency
      ..email = 'customer@email.com'
      ..putMetaData('custom_feilds', [
        {
          'paymentID': '${DateTime.now().millisecondsSinceEpoch}',
        }
      ]);
```
and got this on my backend:
<img width="1725" alt="Screenshot 2022-09-19 at 05 16 46" src="https://user-images.githubusercontent.com/24422971/190928476-d3a7b620-a4e6-4814-97ec-d6990c4099d2.png">

Can you check again?

**Comment by wilburt** [comment]
I am closing this issue since it's been open for some time. Please, feel free to reopen it if the issue persists.

**Comment by quiet-programmer** [comment]
> I am closing this issue since it's been open for some time. Feel free to reopen it if the problem persists.

Thank You I later found a way around it... sorry I didn't close the issue then.
