### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1 in v0.10.0

### ISSUE THREAD

**Issue by papakay** [wilburt/flutter_paystack#11]
Please i'm having this issue after installing the package and trying to run on Android device or build an APK.

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-core-ui' has different version for the compile (27.1.1) and runtime (28.0.0) classpath. You should manually set the same version via DependencyResolution
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 2s
Gradle task assembleDebug failed with exit code 1
```

What can i do please?

**Comment by papakay** [comment]
The work around for now was to use the information provided:

https://github.com/flutter/flutter/issues/14020

**Comment by wilburt** [comment]
OK. Perfect! Is it working now? Can I close this issue now?

**Comment by papakay** [comment]
I really appreciate the great work you put into this package. Please i'll really appreciate if you could improve on the installation document. It was a bit difficult for me to figure out that there's a beautiful UI component for accepting Card details out of the box (PaymentCard). I discovered that after about an hour of trying to find a solution. I believe this will help other developers that would want to use this package.

**Comment by wilburt** [comment]
You mean [CardInputWidget](https://github.com/wilburt/flutter_paystack/blob/master/lib/src/widgets/card_widget.dart)? I actually built it for internal use in the package.

OK. I will see about adding an information about it in the README.

**Comment by papakay** [comment]
I mean the PaymentCard widget that popups the Card Entry form + OTP + PIN and all. Reading through the documentation initially feels like i have to construct those UI my self. It was much later I discovered you already had default UI for it.
