### ISSUE TITLE
Invisible dismiss button

### ISSUE THREAD

**Issue by HahnOnimus** [wilburt/flutter_paystack#111]
![Screenshot_20220217-161124](https://user-images.githubusercontent.com/69061493/154511425-2c814ff6-a34d-4dea-a8fd-bd891b8d78d2.png)

The dismiss buttons not showing up with flutter_paystack: ^1.0.5+1

**Comment by wilburt** [comment]
This cannot be reproduced. Can you check that you're using the correct theme properties? Update to the latest version and reopen this issue if the bug persists.
