### ISSUE TITLE
i'm getting a "Cannot find symbol" error

### ISSUE THREAD

**Issue by mideunlocked** [wilburt/flutter_paystack#113]
While trying to run the project after adding the package to my pubspec.YAML file I'm getting an error 

> 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 10m 2s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
![Screenshot 2022-04-10 at 12 11 18 AM](https://user-images.githubusercontent.com/80066182/162594590-3d94b14b-d214-4e38-80e3-ecde8797290f.png)

**Comment by wilburt** [comment]
This should be fixed in 1.0.6. Can you update the package version?
