### ISSUE TITLE
flutter build apk not working

### ISSUE THREAD

**Issue by theoaks** [wilburt/flutter_paystack#124]
Here's the dump from the output. (Flutter 3.0)

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_paystack-1.0.5+1/lib/src/widgets/sucessful_widget.dart:57:20: Warning: Operand of null-aware operation '
!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) => _startCountdown());
                   ^
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-2.0.3\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java uses unchecked
or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-11.4.1\android\src\main\java\io\flutter\plugins\firebase\messaging\JobIntentService.java
 uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.5+1\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt: (48, 62
): Type mismatch: inferred type is Activity? but Activity was expected
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.5+1\android\src\main\kotlin\co\paystack\flutterpaystack\MethodCallHandlerImpl.kt: (19, 37
): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

**Comment by agentCruz** [comment]
Had the same issue a few days ago.

Update your **pubspec.yaml** file with this:
 flutter_paystack:
   git:
     url: https://github.com/definitelyme/flutter_paystack.git
     ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01

Delete the **pubspec.lock** file
run `flutter clean` then `flutter pub get`

**Comment by wilburt** [comment]
This should be fixed in 1.0.6. Can you update the package version?
