### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getDeviceId on channel plugins.wilburt/flutter_paystack)"

### ISSUE THREAD

**Issue by MonspeetTech** [wilburt/flutter_paystack#127]
Hello chief @wilburt...
I'm always getting this error anytime i try to run paystack in my flutter app..
I have absolutely no idea what's going on

flutter version: 2.10.5
Your response would be highly appreciated... thanks!

**Comment by wilburt** [comment]
Run `flutter clean` and rebuild your project. It should fix it.
