### ISSUE TITLE
recurring subscription with paystack

### ISSUE THREAD

**Issue by bwnyasse** [wilburt/flutter_paystack#13]
Hello , 

I'm trying to use paystack for recunning subscription in my app. 
I am just wondering how can I user the [recurring debits feature](https://developers.paystack.co/docs/recurring-debits)  with flutter_paystack plugin. 

It is possible to have an example ? 
Thank you.

**Comment by wilburt** [comment]
Returning an `authorization_code code` that can be used for subsequent debits should be possible. However, you will have to do future debits on your backend.

**Comment by bwnyasse** [comment]
@wilburt  thank you for your answer. 
As I 've read in the API  , I guess Ijust need to call the [charge authorization](https://developers.paystack.co/v1.0/reference#charge-authorization) with the `authorization_code ` when I want to charge my customer.

I will try to do it. Thank you again with the example/ in the library. Very useful :)

**Comment by wilburt** [comment]
The set of APIs used in the plugin doesn't contain the information as to whether the card can be reused or not. However, after payment with the plugin, you can make a call to your backend which will in turn [verify the transaction](https://developers.paystack.co/v1.0/reference#verify-transaction). The [verification endpoint](https://developers.paystack.co/v1.0/reference#verify-transaction) contains information of the reusability of the card (including the authorization code).

Please, let me know if you need further clarification or assistance.
