### ISSUE TITLE
The prices are in NGN even though I am using GHS (Ghana cedis). It doesn't work for Ghana's API.

### ISSUE THREAD

**Issue by decwap** [wilburt/flutter_paystack#132]
It doesn't change when I use Ghana cedis. The figures appear in NGN even though my app prices are in GHS. 
Can anyone help?

**Comment by wilburt** [comment]
@decwap  Can you send a screenshot of the UI and some code samples?

**Comment by decwap** [comment]
Thank you very much, is there a way I can get the Mobile Money part too, it only displays card payments. Please help.

![Screen Recording 2020-03-05 at 08 45 PM](https://user-images.githubusercontent.com/4895642/191139949-126ef130-c442-4fbc-ab89-9b87c13efb1c.gif)

**Comment by wilburt** [comment]
There are currently no plans to support Mobile Money, but you can implement it and raise a PR. I will be closing this issue since the problem has been fixed.
