### ISSUE TITLE
Paystack library

### ISSUE THREAD

**Issue by iliasHB** [wilburt/flutter_paystack#134]
hello sir, 

I have a serious issues with flutter paystack checkout page. The paystack checkout page is working fine on IOS mobile but is not running on android. Please, I need your support because i am really running out of time. I have other things i want to explain, i will like to have a voice conversation with the developer, please can you share your contact and you can reach me on 08074730367.

flutter_paystack 1.0.5+1 gave me this error below when I try to build my application on android mobile
--------------------------------------------------------------------------------------------------------------------------
e: C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_paystack-1.0.5+1\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt: (48, 62): Type mismatch: inferred type is Activity? but Activity was expected
e: C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_paystack-1.0.5+1\android\src\main\kotlin\co\paystack\flutterpaystack\MethodCallHandlerImpl.kt: (19, 37): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_paystack:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s
Exception: Gradle task assembleDebug failed with exit code 1

-----------------------------------------------------------------------------------------

flutter_paystack 1.0.6 gave me this error below when I try to installed the dependency, the dependency refuse to install with this errror below
-------------------------------------------------------------------------------------
Because every version of flutter_test from sdk depends on meta 1.7.0 and flutter_paystack >=1.0.6 depends on meta ^1.8.0, flutter_test from sdk is incompatible with flutter_paystack >=1.0.6.
So, because paystackflutter depends on both flutter_paystack ^1.0.6 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because paystackflutter depends on both flutter_paystack ^1.0.6 and flutter_test from sdk, version solving failed.)
-----------------------------------------------------------------------------------------------

**Comment by wilburt** [comment]
Add this to the pubspec.yaml:
```
dependency_overrides:
  meta: 1.7.0
```

**Comment by wilburx9** [comment]
Closing this since there's no response from OP.
