### ISSUE TITLE
Upgrading package to new version broke my app

### ISSUE THREAD

**Issue by papi-knomic** [wilburt/flutter_paystack#136]
I recently upgraded to Flutter 3 and also decided to upgrade packages, the paystack package doesn't seem to work anymore when I'm trying to debug

I get this error
![main dart - mealtrips_user - Visual Studio Code 06_10_2022 18_41_56](https://user-images.githubusercontent.com/57762107/194724221-b099644b-063b-4daf-9756-1e8509e9b138.png)

The error is coming from this particular file 
![main dart - mealtrips_user - Visual Studio Code 06_10_2022 18_42_28](https://user-images.githubusercontent.com/57762107/194724249-b978762a-1ac2-4907-9e30-933d790e83d5.png)

**Comment by Emmakade** [comment]
i

> I recently upgraded to Flutter 3 and also decided to upgrade packages, the paystack package doesn't seem to work anymore when I'm trying to debug
> 
> I get this error ![main dart - mealtrips_user - Visual Studio Code 06_10_2022 18_41_56](https://user-images.githubusercontent.com/57762107/194724221-b099644b-063b-4daf-9756-1e8509e9b138.png)
> 
> The error is coming from this particular file ![main dart - mealtrips_user - Visual Studio Code 06_10_2022 18_42_28](https://user-images.githubusercontent.com/57762107/194724249-b978762a-1ac2-4907-9e30-933d790e83d5.png)

i got this error too, how can it be fixed? @Itope84 @wilburt  please help us
