### ISSUE TITLE
material-1.5.0-alpha03\res\values-v31\values-v31.xml:3:5-94: AAPT: error: resource android:color/system_neutral1_1000 not found

### ISSUE THREAD

**Issue by johnebere58** [wilburt/flutter_paystack#137]
To resolve this kindly update the compileSdkVersion to 31 in the build.gradle file

**Comment by javarava** [comment]
I'm getting the same errors and my compileSdkVersion is 33

**Comment by Emmakade** [comment]
i got the same error, What's the way forward? @wilburt  please help us @nuelsoft

**Comment by javarava** [comment]
@Emmakade I ended up using the Webview option in PayStack doc at https://paystack.com/docs/guides/using_the_paystack_checkout_in_a_mobile_webview/

**Comment by insysinfo** [comment]
please upgrade flutter_paystack's android > build.gradle like below SS..
sdk version 31 or more than 31

![image](https://user-images.githubusercontent.com/70749329/209277364-6c45ac76-9ae7-4c7e-8b3e-e8d5001b3597.png)
