### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by Seedorf161** [wilburt/flutter_paystack#14]
Got the error below. Please help

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_paystack' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by wilburt** [comment]
The Kotlin version used in the plugin is a bit out of date. I have plans to update the dependencies and convert to AndroidX in the version.

For in the interim, you can manually update the Kotlin version in ...pub-cache/hosted/pub.dartlang.org/flutter_paystack-1.0.0/android/build.gradle.

**Comment by Seedorf161** [comment]
Fix that by changing my project gradle version to 3.2.1
