### ISSUE TITLE
APK not generating (Using latest flutter version)

### ISSUE THREAD

**Issue by wrteam-vimal** [wilburt/flutter_paystack#141]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_paystack:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:3:5-94: AAPT: error: resource android:color/system_neutral1_1000 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:4:5-94: AAPT: error: resource android:color/system_neutral1_900 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:5:5-93: AAPT: error: resource android:color/system_neutral1_0 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:6:5-94: AAPT: error: resource android:color/system_neutral1_800 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:7:5-94: AAPT: error: resource android:color/system_neutral1_700 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:8:5-94: AAPT: error: resource android:color/system_neutral1_600 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:9:5-94: AAPT: error: resource android:color/system_neutral1_500 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:10:5-94: AAPT: error: resource android:color/system_neutral1_400 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:11:5-94: AAPT: error: resource android:color/system_neutral1_300 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:12:5-94: AAPT: error: resource android:color/system_neutral1_200 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:13:5-94: AAPT: error: resource android:color/system_neutral1_100 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:14:5-93: AAPT: error: resource android:color/system_neutral1_50 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:15:5-93: AAPT: error: resource android:color/system_neutral1_10 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:16:5-102: AAPT: error: resource android:color/system_neutral2_1000 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:17:5-102: AAPT: error: resource android:color/system_neutral2_900 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:18:5-101: AAPT: error: resource android:color/system_neutral2_0 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:19:5-102: AAPT: error: resource android:color/system_neutral2_800 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:20:5-102: AAPT: error: resource android:color/system_neutral2_700 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:21:5-102: AAPT: error: resource android:color/system_neutral2_600 not found.

     ERROR:/home/ubuntu/.gradle/caches/transforms-3/a15c43a196a953d5361e55fcf30c92a2/transformed/material-1.8.0-alpha01/res/values-v31/values-v31.xml:22:5-102: AAPT: error: resource android:color/system_neutral2_500 not found.

**Comment by codearemo** [comment]
Currently facing this issue. 😢😢😢😢
Please can someone help with a solution.

**Comment by wrteam-vimal** [comment]
> Currently facing this issue. crycrycrycry Please can someone help with a solution.
@codearemo  sir you can use this one 

flutter_paystack:
  git:
    url: https://github.com/definitelyme/flutter_paystack.git
    ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01

Instead of 
flutter_paystack:^x.x.x

Thank you!

**Comment by mbaka-bilal** [comment]
I don't understand the answer can you help please @wrteam-vimal @codearemo
