### ISSUE TITLE
PayStack stopped working:  type 'int' is not a subtype of type 'String?'

### ISSUE THREAD

**Issue by Megagonn** [wilburt/flutter_paystack#145]
`var res =await PayNow(
                            name: data['name'],
                            quantity: '1',
                            email: data['email'],
                            price: int.parse(serviceFee) * 100,
                            ctx: context,
                            argument: data,
                          ).chargeNow();`
`Charge charge = Charge()
      ..amount = price
      ..email = email
      ..reference = _getRef()
      ..card = cardUi()
      ..currency = "NGN";

    CheckoutResponse checkoutResponse = await paystack.checkout(
      ctx,
      charge: charge,
      method: CheckoutMethod.card,
      logo: Image.asset(
        "assets/images/logo.png",
        width: 120,
      ),
    );`

![p1](https://user-images.githubusercontent.com/94833408/209310529-2cab56bb-a6d9-4306-9d54-63a8e7284c41.png)
![p2](https://user-images.githubusercontent.com/94833408/209310539-48f98a7c-a945-46b7-b20d-3109c97a7c93.png)

**Comment by Megagonn** [comment]
It was working perfectly until some days ago.

**Comment by iamVictorSam** [comment]
I'm having the same error. 
App was working perfectly fine on Friday 23 December 2022

**Comment by DeveloperMaleek** [comment]
I am having the same error.

**Comment by iamVictorSam** [comment]
can this be looked into @wilburt 
my app is depending on this.

**Comment by wilburt** [comment]
> can this be looked into @wilburt 
> 
> my app is depending on this.

@iamVictorSam Sure, it can. What are the steps to reproducing it?

**Comment by wilburt** [comment]
@Megagonn  @DeveloperMaleek  How do I reproduce it? [All test cards and banks](https://paystack.com/docs/payments/test-payments/) are working for me with no issues.

**Comment by DeveloperMaleek** [comment]
After initializing the plugin with my pubic key in my init state, this is what my test function is and thus return the error.

`Future<void> payWithPaystack(
    BuildContext context,
  ) async {
    Charge charge = Charge()
      ..amount = 10000
      ..reference = 'thisisref'
      ..email = 'malikademola36@gmail.com';
    try {
      CheckoutResponse response = await plugin.checkout(
        context,
        logo: Image.asset(
          'assets/images/kawe-logo.png',
        ),
        fullscreen: true,
        method: CheckoutMethod.card, // Defaults to CheckoutMethod.selectable
        charge: charge,
      );
      print(response);
    } catch (e) {
      print(e);
    }
  }`

**Comment by wilburx9** [comment]
So, it just throws `type 'int' is not a subtype of type 'String?'` when you call`payWithPaystack()`? Do you know if it shows the card UI dialog at all? 

I still can't reproduce the error. I used the same function above (without the logo param) and made a successful payment.

**Comment by DeveloperMaleek** [comment]
It shows the Card UI dialog, the error shows up after inputing the test card details and clicking on Pay 100.

**Comment by wilburx9** [comment]
Interesting. Can you send me a screen recording of the flow from app launch to when the error appears?

**Comment by DeveloperMaleek** [comment]
I'll do that shortly.

**Comment by DeveloperMaleek** [comment]
While testing it out, it no longer shows the error.

**Comment by wilburx9** [comment]
Ok. No worries. Update here if it happens again.
