### ISSUE TITLE
Invalid amount passed

### ISSUE THREAD

**Issue by usmanabdulmajid** [wilburt/flutter_paystack#156]
For card checkout, the amount passed through charge is not formatted correctly. 
```dart
static String formatAmount(num amountInBase) {
    if (_currencyFormatter == null) throw "Currency formatter not initialized.";
    return _currencyFormatter!.format((amountInBase / 100));
  }
````
https://github.com/wilburt/flutter_paystack/blob/98d93d32df9a368a923bffd375e7b9479c85f85f/lib/src/common/utils.dart#L19

Amount is divided by 100, which alters the value entered by users.

**Comment by wilburx9** [comment]
This is a documented behaviour and is behaving as expected.
https://github.com/wilburt/flutter_paystack/blob/98d93d32df9a368a923bffd375e7b9479c85f85f/lib/src/models/charge.dart#L15

**Comment by abdulkash** [comment]
when creating a charge object if i set the amount to be 10,000 on the paystack ui it shows 100.0 
`Charge charge = Charge()`
                          `..amount = plan.amount`
                         ` ..reference = reference`
                          `..email = 'customer@email.com';`
i think there is an issue with your currency formatter
