### ISSUE TITLE
Access code has expired

### ISSUE THREAD

**Issue by mopilo** [wilburt/flutter_paystack#16]
I keep getting **Access code has expired** and transaction keeps repeating it self because of this line

`    
           if (e is ExpiredAccessCodeException) {
             _startAfreshCharge();
            _chargeCard(charge);
            print(e);
           return;
}
`

**Comment by mopilo** [comment]
fixed this by using charge.reference

**Comment by wilburt** [comment]
@mopilo Please, can you link the class in question?

**Comment by mopilo** [comment]
Sorry what class?

**Comment by wilburt** [comment]
The class where this line `if (e is ExpiredAccessCodeException) { _startAfreshCharge(); _chargeCard(charge); print(e); return; }` was found.

**Comment by wilburt** [comment]
I will have to close this issue since clarification wasn't provided. Please, feel free to reopen when you are able to provide further clarification.
