### ISSUE TITLE
Incorrect charge amount 

### ISSUE THREAD

**Issue by abdulkash** [wilburt/flutter_paystack#161]
when creating a charge object if i set the amount to be 10,000 on the paystack ui it shows 100.0 
`Charge charge = Charge()`
                          `..amount = plan.amount`
                         ` ..reference = reference`
                          `..email = 'customer@email.com';`
i think there is an issue with your currency formatter

**Comment by yourstrulycreator** [comment]
This is still an issue, why is it closed
