### ISSUE TITLE
Failed android build

### ISSUE THREAD

**Issue by mtellect** [wilburt/flutter_paystack#2]
I must say , the library is brilliant. works well on ios out of the box without any complex form of configuration, but on android fails to build completely 
with these completely annoying error

e: /Users/iammaugost/.pub-cache/hosted/pub.dartlang.org/flutter_paystack-0.9.1+1/android/src/main/kotlin/co/paystack/flutterpaystack/FlutterPaystackPlugin.kt: (44, 44): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_paystack:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 10s    

..please help look into it

**Comment by mtellect** [comment]
Solved!!!...
Locate the FlutterPaystack.kt file located on the android side of the plugin and
Replace @line44
val encryptedData = Crypto.encrypt(call.argument<String>("stringData"))
with :
val encryptedData = Crypto.encrypt(call.argument<String>("stringData").toString())

boom!! your good to go...
for the record the library is superb!!!

**Comment by wilburt** [comment]
Thanks for this. Strangely, I am not getting such an error. 

Please, can you make a pull request with this fix?

**Comment by Emmakade** [comment]
> Solved!!!... Locate the FlutterPaystack.kt file located on the android side of the plugin and Replace @line44 val encryptedData = Crypto.encrypt(call.argument("stringData")) with : val encryptedData = Crypto.encrypt(call.argument("stringData").toString())
> 
> boom!! your good to go... for the record the library is superb!!!

Weldone, my own version is version 1.0.6 and all the code lines including bracing bracket is 42
