### ISSUE TITLE
Processing Paystack payment error

### ISSUE THREAD

**Issue by Bendevet** [wilburt/flutter_paystack#28]
I couldn't complete payment on Paystack. It keeps showing "loading..." icon without throwing any error or terminating the process.

**Comment by wilburt** [comment]
That's strange. Mind sharing the piece of code?

**Comment by Bendevet** [comment]
Yes, of course. Here are the code snippets
________________________________

**Comment by wilburt** [comment]
@Bendevet  It appears you forgot to paste the code snippet.

**Comment by Bendevet** [comment]
<img width="333" alt="Screen Shot 2020-01-10 at 4 04 38 PM" src="https://user-images.githubusercontent.com/56494608/72186456-5707f500-33c3-11ea-8c71-c6c7546a9bbd.png">
<img width="643" alt="Screen Shot 2020-01-10 at 4 05 11 PM" src="https://user-images.githubusercontent.com/56494608/72186457-5707f500-33c3-11ea-8e4c-cfb455a60dd2.png">
<img width="432" alt="Screen Shot 2020-01-10 at 4 06 01 PM" src="https://user-images.githubusercontent.com/56494608/72186458-5707f500-33c3-11ea-9889-bb2326f27da5.png">

**Comment by thebigtank** [comment]
Has this been resolved? I'm facing same issue right now

**Comment by thebigtank** [comment]
your access code needs to be unique for each request

**Comment by Bendevet** [comment]
I changed my access it's still same error

**Comment by Bendevet** [comment]
I've changed access code but I'm still getting the same error

**Comment by Bendevet** [comment]
solved for now:
so I needed to add this " method: CheckoutMethod.card"  and then use reference instead of access code.
thanks.

**Comment by wilburt** [comment]
@Bendevet  Since you have found the solution, I guess I will have to close this issue. Please, feel free to reopen it if it reoccurs.
