### ISSUE TITLE
Android dependency issues preventing build

### ISSUE THREAD

**Issue by solnsumei** [wilburt/flutter_paystack#3]
Awesome plugin. Although I am not able to build on Android. It throws this error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-fragment' has different version for the compile (27.1.1) and runtime (28.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

Any advice on how to solve this is highly appreciated. Thanks.

**Comment by wilburt** [comment]
Hello, please are you trying to build the project or you're using the library in another project?

**Comment by wilburt** [comment]
Please, ensure that you're using version 28.0.0 of the support libraries.

**Comment by solnsumei** [comment]
I updated but got the expected string error as mentioned in the closed issues. Please fix.

**Comment by wilburt** [comment]
The string error was fixed in version `0.9.1+2` of this library. Please, can you update?
