### ISSUE TITLE
 set the currency to paystack flutter plugin, but the dialog still display NGN

### ISSUE THREAD

**Issue by angeldragon** [wilburt/flutter_paystack#30]
we set the currency to paystack flutter plugin, but still display NGN

**Comment by wilburt** [comment]
My bad--I replicate and fix.

**Comment by wilburt** [comment]
I believe the issue has been fixed. Please, reopen if you can still replicate it.

**Comment by angeldragon** [comment]
OK，I have verified and solved，very thanks,
But I found two other problems:
The first: Cannot delete by long pressing the delete button of the floppy disk on the card number input page;
The second: Error after entering invalid year or month

**Comment by wilburt** [comment]
OK. Thank you.

Please, check the issues raised; I believe have addressed them.
