### ISSUE TITLE
App stopped while running headless service.

### ISSUE THREAD

**Issue by Solesty** [wilburt/flutter_paystack#31]
The plugin works fine for transactions and that is great.
My app has an audio player and it runs in the background, any time the play button has been tapped the app crashed and the following stack trace is given.

java.lang.IllegalStateException: registrar.activity() must not be null
**E/AndroidRuntime(14901): 	at co.paystack.flutterpaystack.FlutterPaystackPlugin$Companion.registerWith(FlutterPaystackPlugin.kt:18)**
E/AndroidRuntime(14901): 	at co.paystack.flutterpaystack.FlutterPaystackPlugin.registerWith(Unknown Source:2)
E/AndroidRuntime(14901): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:29)

I am guessing you will need to guard against Headless service which doesn't have an activity in them.

**Comment by wilburt** [comment]
Thanks for pointing this out. I will fix it ASAP.

**Comment by wilburt** [comment]
I believe the issue has been fixed. Please, reopen if you can still replicate it.
