### ISSUE TITLE
Cannot delete by long pressing the delete button of the floppy disk in the card number input box

### ISSUE THREAD

**Issue by angeldragon** [wilburt/flutter_paystack#38]
Cannot delete by long pressing the delete button of the floppy disk in the card number input box

**Comment by wilburt** [comment]
The icon displayed to the right of the card number text field indicates the card issuer. Sometimes, a generic card icon (I believe that's what you're referring to as "floppy disk") is displayed if the issuer can't be determined by the current numbers the user has entered. 

The icon isn't meant to be clicked.

**Comment by angeldragon** [comment]
No, when I enter the completed card number, I ca n’t delete by pressing and holding the keyboard delete button

**Comment by angeldragon** [comment]
My  huawei P10
