### ISSUE TITLE
Reference value received after transaction different from the one used to initialize the transaction

### ISSUE THREAD

**Issue by solnsumei** [wilburt/flutter_paystack#4]
I tried using the plugin to create a transaction but found out the reference returned after the transaction is different from the one I passed in. Is there any rationale why the reference I create is not being returned or is it omitted from paystack's end?

**Comment by wilburt** [comment]
This could be a bug and it is quite strange. The reference should be the same. Please, can you send a sample code of how you're doing it?

**Comment by solnsumei** [comment]
_handleCheckout() async {
    final _reference = 'TXN' + Random().nextInt(4294967296).toString();
    print('Reference Passed: $_reference');

    Charge charge = Charge()
      ..amount = 10000
      ..email = 'user@mydomain.com'
      ..transactionCharge = 3000
      ..currency = 'NGN'
      ..reference = _reference
      ..putCustomField('Mobile Number', '+2348030000000');

    CheckoutResponse response = await PaystackPlugin.checkout(
      context,
      method: CheckoutMethod.selectable,
      charge: charge,
    );

    print('Response = $response');
  }

Result for the transaction 

`
flutter: Reference Passed: TXN1464888487
flutter: Response = [Message: Approved, 
Card: null, 
Account: [Bank: [Name: Zenith Bank, Code: 057], Number: 0000000000], 
Reference: ecwbfv2xej5zwnv, 
Method: CheckoutMethod.bank, 
Status: true]
`
.....................................
Secondly the transaction Charge does not show up to let the users know there is a transaction charge.

**Comment by solnsumei** [comment]
Also If I opt to use the Charge card option I am required to also input my secret key.

**Comment by wilburt** [comment]
> Also If I opt to use the Charge card option I am required to also input my secret key.

No, the secret key is not needed for charge card option.

**Comment by wilburt** [comment]
> Secondly the transaction Charge does not show up to let the users know there is a transaction charge.

Please, can you expatiate on this?

**Comment by wilburt** [comment]
> Is there any rationale why the reference I create is not being returned or is it omitted from paystack's end?

The fault is mine--for bank account payment, I wasn't sending the reference to Paystack. I will fix it and push an update ASAP.

Thanks for raising this issue.

**Comment by solnsumei** [comment]
ok cool, thanks. Good job
