### ISSUE TITLE
Missing file in the new version

### ISSUE THREAD

**Issue by Seedorf161** [wilburt/flutter_paystack#45]
I just upgraded to the latest version 1.0.3 and i"m getting the error below which suggests a file is missing.

> Couldn't read file LocalFile:
> '/Users/omotayo/flutter_paystack/android/src/main/kotlin/io/flutter/plugins/webviewflutter/WebViewF
> lutterPlugin.kt' even though it exists. Please verify that this file has read permission and try
> again.

**Comment by wilburt** [comment]
Thank you. Please, update to `1.0.3+1`.
