### ISSUE TITLE
Make OTP input field  hint generic

### ISSUE THREAD

**Issue by wilburt** [wilburt/flutter_paystack#47]
The [OTP widget](https://github.com/wilburt/flutter_paystack/blob/master/lib/src/widgets/otp_widget.dart)  is currently being used not only for an actual OTP input but for any other non-pin numeric authentication input. 

And the hint text currently says "OTP". This is misleading to users when the input requires anything other than an actual OTP,  e.g a phone number.

See screenshot:

![image](https://user-images.githubusercontent.com/24422971/73607725-27ab6900-45ba-11ea-8369-57bab4c372ab.png)

**Comment by DAMMAK** [comment]
What do you think should be there... I'm thinking about fixing this along with #48  since they are both on the same widget.

**Comment by wilburt** [comment]
I honestly don't know what should be there yet. Do you have any idea?
