### ISSUE TITLE
OTP input field should be alphanumeric

### ISSUE THREAD

**Issue by wilburt** [wilburt/flutter_paystack#48]
There's a current restriction on the OTP input field that makes it accept only numeric characters. I feel this should be loosened up. Though I have never heard of cases where banks send alphanumeric OTP, I don't think it would hurt to remove this restriction and make this field accept other characters.

Another case for removing this restriction is that the OTP input is also used for other authentication inputs. So this means if the authentication flow requires something like the user's mother's maiden name, the user would get stuck.

**Comment by DAMMAK** [comment]
should I try to work on this

**Comment by wilburt** [comment]
> should I try to work on this

Yes, please. Thank you.
