### ISSUE TITLE
Checkout Dialog too small.

### ISSUE THREAD

**Issue by jerryOkafor** [wilburt/flutter_paystack#5]
I think we can increase the size of the Checkout Dialog by using a fulscreen dialog instead.

**Comment by wilburt** [comment]
@jerryOkafor The actual reason why I went for a centred non-fullscreen dialog was an attempt to replicate the design of the official Paystack checkout UI.

Please, why do you think we should make it fullscreen?

**Comment by wilburt** [comment]
@jerryOkafor The actual reason why we went for a centred non-fullscreen dialog was an attempt to replicate the design of the Paystack web checkout UI. 

You have a point though. PCs and mobile phone don't have the same screen real-estate.

Maybe we should add an optional fullscreen dialog. The configuration parameter can be passed to the `checkout` function. What do think about this?

**Comment by jerryOkafor** [comment]
That would be nice. I was working on something before now, first choice was a dialog but it did not give me all I wanted and I made it a fullscreen. I am sure fullscreen would be nice.
