### ISSUE TITLE
Project fails to build after adding dependency

### ISSUE THREAD

**Issue by olufemioyedepo** [wilburt/flutter_paystack#54]
My project is not building anymore after adding the **flutter_paystack: ^1.0.3+1** to the pubspec.yaml file. 
Error on debug console: **Couldn't read file LocalFile: 'C:\flutter code\playground\android\src\main\kotlin\co\paystack\flutterpaystack\FlutterPaystackPlugin.kt' even though it exists. Please verify that this file has read permission and try again.**

**Comment by DEVSOG12** [comment]
Hi, 
Do a flutter doctor and let me see how I can assist you?

**Comment by wilburt** [comment]
With no response from the author, I am sorry I have to close this issue.
Please, feel free to reopen it if the issue persists.
