### ISSUE TITLE
MissingPluginException(No implementation found for method getUserAgent on channel flutter_paystack)

### ISSUE THREAD

**Issue by Adex9ja** [wilburt/flutter_paystack#55]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getUserAgent on channel flutter_paystack)
E/flutter (24457): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (24457): <asynchronous suspension>
E/flutter (24457): #1      PaystackPlugin.initialize (package:flutter_paystack/src/common/paystack.dart:50:48)
E/flutter (24457): #2      _PaymentActivity.initState (package:mykab/ui/activities/payment_gateway.dart:28:20)
E/flutter (24457): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (24457): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (24457): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (24457): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24457): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24457): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (24457): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (24457): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (24457): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (24457): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24457): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24457): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (24457): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (24457): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (24457): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (24457): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (24457): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24457): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24457): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (24457): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (24457): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (24457): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (24457): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (24457): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24457): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24457): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart

**Comment by DEVSOG12** [comment]
Hi. 
I’m George 
I have come across this error before   
Go to your build.gradle then app multidex enable:true in the default config 

Like this
android {
    compileSdkVersion 22
    buildToolsVersion "23.0.0"

         defaultConfig {
             minSdkVersion 21 //lower than 14 doesn't support multidex
             targetSdkVersion 22
               //Right Here
             // Enabling multidex support.
             multiDexEnabled true


If I doesn’t work you can reach me on oreofesolarin@gmail.com
