### ISSUE TITLE
How to Navigate after payment is Successful

### ISSUE THREAD

**Issue by DEVSOG12** [wilburt/flutter_paystack#56]
I need help really fast in navigation if the payment is successful

**Comment by oyeolamilekan** [comment]
And a navigator.push in the onSuccess method of the transaction

**Comment by DEVSOG12** [comment]
Thanks I figured that out earlier. If I'm using the app for production can I still rely in the simple charge backend on heroku or is there any other way I can use.

**Comment by wilburt** [comment]
The simple charge backend from Heroku, I believe, is just for demo purposes. Please, can I close this since you've figured out the solution to your original issue?

**Comment by DEVSOG12** [comment]
Thanks 🙏
