### ISSUE TITLE
update amount

### ISSUE THREAD

**Issue by eshanokpe** [wilburt/flutter_paystack#59]
please how do i update each user record. Especially the amount

**Comment by eshanokpe** [comment]
like to add up the user deposit. If the user deposited 100, and later 200.
How do I add the transaction together

**Comment by wilburt** [comment]
Hi @eshanokpe,
Please this is beyond the scope of this package, you might want to contact the Paystack team for this.

**Comment by eshanokpe** [comment]
OK please how about how do I withdraw from the app.

**Comment by eshanokpe** [comment]
please and also to send money to some one else. How do I do that with the
paystack package with flutter. Thank you sir

**Comment by eshanokpe** [comment]
Please how do I withdrawn and send money with the package. Thanks
