### ISSUE TITLE
FlutterPaystackPlugin.h' file not found

### ISSUE THREAD

**Issue by jerryOkafor** [wilburt/flutter_paystack#6]
I get this error `flutter_paystack/FlutterPaystackPlugin.h' file not found` when I open my flutter project in Xcode, it started happening the moment I added the flutter_paystack to the app.

**Comment by wilburt** [comment]
Please see [#16036](https://github.com/flutter/flutter/issues/16036#issuecomment-380712094) for how to resolve this.
