### ISSUE TITLE
Pay with mobile money feature

### ISSUE THREAD

**Issue by rrijal53** [wilburt/flutter_paystack#63]
Pay with mobile money option is not available in this sdk.

**Comment by leomaxi** [comment]
An issue ⚠️.. Need direction on this

**Comment by rishav00a** [comment]
i am also getting the same issue !!!

i tried initiating payment with parameter channels with value ['card', 'bank', 'ussd', 'qr', 'mobile_money', 'bank_transfer']

i am getting only two options

Card
Bank

**Comment by leadenpraise** [comment]
hi! has anyone been able to add mobile money to this plugin?

**Comment by leadenpraise** [comment]
Mobile money payment method is not available from the Flutter SDK, however, you can integrate directly into the API to add mobile money option in your app.

Here's our documentation for this => https://paystack.com/docs/payments/payment-channels/#mobile-money 


can anyone help on how to make this work with the plugin?

**Comment by nyelnizy** [comment]
i guess i would have to switch to flutterwave and switch back later on.

**Comment by leadenpraise** [comment]
any update on the momo feature adding to the plugin?

**Comment by wilburt** [comment]
@leadenpraise I don't have any plans to support mobile money as it requires exposing the secret key on the client.

**Comment by leadenpraise** [comment]
@wilburt i understand from that angle. but is there a way to help some of us who need the mobile money option? because the plugin will be useless to us without the mobile money option because that's the basic payment channel for Ghana.

**Comment by wilburt** [comment]
@leadenpraise the only suggestion I can think of is that when it's time for the user to pay, you send an API request to your backend which will generate a Paystack payment URL attached to that user. When the request returns, you grab the payment URL from it and send the user to a WebView. Listen for when the WebView is closed and send another request to your backend to check the status of the payment. When this request returns,  display a UI to the user that matches the status of the transaction.

**Comment by Daniel-Sogbey** [comment]
@leadenpraise use this ,```https://paystack.com/docs/payments/payment-channels/#mobile-money```, to directly interact with the charge api.

**Comment by Felix-Asante** [comment]
> @leadenpraise use this ,`https://paystack.com/docs/payments/payment-channels/#mobile-money`, to directly interact with the charge api.

 is it possible to create a charge and ask the user to authorize it by just validating the charge with his/her mobile money pin?
