### ISSUE TITLE
Issue with amount

### ISSUE THREAD

**Issue by Keithwachira** [wilburt/flutter_paystack#64]
For some reason the Sdk divides my amount by 100.E.g if i want to  pay 2000 it shows 200.
![Screen Shot 2020-09-11 at 10 03 56 AM](https://user-images.githubusercontent.com/8012032/92879883-1ced6800-f416-11ea-8df1-cca12543ac93.png)
![Screen Shot 2020-09-11 at 10 04 38 AM](https://user-images.githubusercontent.com/8012032/92880128-5c1bb900-f416-11ea-926a-943e8b0b7e12.png)

**Comment by wilburt** [comment]
That's intentional. You're supposed to pass the amount in kobo.

**Comment by Keithwachira** [comment]
What do you mean by Kobo?

**Comment by wilburt** [comment]
It's the smallest subunit of the Naira, the Nigerian currency.

**Comment by wilburt** [comment]
I would advice that you multiply the text field value by 100 before passing it to the plugin.

**Comment by Keithwachira** [comment]
Thanks for your response.I think you should write this on the documentation or allow users to state they want to use kobo explicitly with a parameter  ,i am not from Nigeria  i didn't know that.
Thank you again for the response.

**Comment by wilburt** [comment]
For future references, there's already documentation for this and it can be found [here](https://pub.dev/documentation/flutter_paystack/latest/flutter_paystack/Charge/amount.html).
