### ISSUE TITLE
Add support for Paystack's check authorization feature

### ISSUE THREAD

**Issue by egbinola** [wilburt/flutter_paystack#66]
The Paystack **_['check authorization](https://paystack.com/docs/api#transaction-check-authorization)_**' feature allows advance checks on cards to know if they have enough funds for payment (mostly for a later period).

**Comment by wilburt** [comment]
Thank you for the feature request @egbinola. I am afraid it won't be supported on this plugin since it requires the secret key to implement. This feature is better suited for the backend of your mobile application.

**Comment by egbinola** [comment]
Okay. Thank you.
