### ISSUE TITLE
Plugin converts my int to double how can I change this, API I'm sending too does not need double but int

### ISSUE THREAD

**Issue by quiet-programmer** [wilburt/flutter_paystack#69]
Plugin converts my int to double how can I change this, API I'm sending too does not need double but int.

I need help because this plugin automatically converts 100 to 1.00 and send as payment, is there any way I can make this just send 100 instead of 1.00.

**Comment by wilburt** [comment]
Hello @quiet-programmer  As mentioned in #64, amounts should be passed in the base currency. So for example, if you need a payment of 100, pass 10000 to the `charge` object.

**Comment by quiet-programmer** [comment]
Thanks for the response, I later found another way to bypass that kobo issue. Thanks for the help and I love the plugin.

**Comment by JoelOvien** [comment]
> Thanks for the response, I later found another way to bypass that kobo issue. Thanks for the help and I love the plugin.

Please what other way did you make use of?
