### ISSUE TITLE
Minimum flutter version

### ISSUE THREAD

**Issue by faithomotoso** [wilburt/flutter_paystack#70]
I have flutter 1.20 installed and when I tried to add the package it says minimum flutter version supported is 1.20.1. Do I have to upgrade my flutter version before I use this package?

**Comment by asapJ** [comment]
Hi, if you are still on flutter 1.20 you could either:
1. Check the change log, downgrade the plugin to a version before the minimum flutter SDK bump.

2. Upgrade your flutter version to the latest on the stable channel.

**Comment by wilburt** [comment]
@faithomotoso  I am closing this issue for now. Please, feel free to reopen it if @asapJ's suggestion doesn't work for you.
