### ISSUE TITLE
Plugin undercharges users even after specifying correct amount in Kobo.

### ISSUE THREAD

**Issue by asapJ** [wilburt/flutter_paystack#71]
I noticed that the plugin undercharges each transaction amounts, even after specifying the right Kobo equivalent. So apparently I think it further devises the actual amount by 100.
I attached a screenshot.

Note the original amount at the top of the base widget and the amount the modal. The formatting seems off too.

Current flutter version: 1.22.0

**Comment by asapJ** [comment]
![PicsArt_10-14-04 07 10](https://user-images.githubusercontent.com/33837248/96008416-7262cd80-0e37-11eb-950d-830b0d5776ad.jpg)

**Comment by wilburt** [comment]
Please, what value did you pass to the charge object?

**Comment by asapJ** [comment]
> Please, what value did you pass to the charge object?

The amount to charge was 1500, so I passed 1500 * 100 which should give the Kobo equivalent. If you observe that image, you will notice that the correct and actual amount (1500) showed at the top but the OTP modal seems to further divide that actual value by 100 again resulting in showing 15.00.

Refer to the attached image.

**Comment by wilburt** [comment]
@asapJ  Yeah, seen. I just wanted to be certain you were passing 1500 * 100. Please did this happen in production?

**Comment by asapJ** [comment]
> @asapJ Yeah, seen. I just wanted to be certain you were passing 1500 * 100. Please did this happen in production?

No, I am still using test keys/cards..
But I hope it hasn't slipped into production for others, lol. I saw a similar issues here, but the author did not quite explain in details and it was closed..

**Comment by wilburt** [comment]
As you might have already known, you need to pass an access code for bank account payment. Now, the access code generation endpoint requires an amount. Hence, when you pass the returned access code to the charge object, Paystack ignores the amount field in the charge object and uses the amount passed to the access code generation endpoint.

So, in summary, your backend is passing 1500 kobo to paystack while generating the access code.

**Comment by asapJ** [comment]
Oh.. let me revert back to the BE Engineer.

**Comment by asapJ** [comment]
@wilburt the issue has been resolved. It was as you said. The backend Engineer didn't convert amounts to Kobo before passing to the paystack initialisation endpoint.
Thanks for your help.
