### ISSUE TITLE
Unable to get metadata from webhook callback

### ISSUE THREAD

**Issue by Nigeriancoder** [wilburt/flutter_paystack#72]
Hi @wilburt! Great work on this library.
Just one issue. I'm unable to get the metadata passed to the charge object when I get the callback on my webhook. 
Here's my charge object.

Charge charge = Charge()
      ..amount = _amount * 100
      ..accessCode = accessCode["data"]["access_code"]
      ..email = 'customer@email.com'
       ..putMetaData("payment_data", [
      {
           'action': 'fund-wallet',
           'customer_id': bucket.accountObject.items[0].customerId
         }
      ]);

Metadata comes in as null. I'd really appreciate your help.
Thanks.

**Comment by Nigeriancoder** [comment]
@wilburt Any feedback?

**Comment by wilburt** [comment]
@Nigeriancoder  Please, can you show the full code including the payment method?

**Comment by wilburt** [comment]
Closing this for now since there's been no response from OP. Please, reopen if the issue persists.

**Comment by quiet-programmer** [comment]
@Nigeriancoder have you found a way around this?
