### ISSUE TITLE
This plugin doesnt have all the features on the web(javascript) plugin. 

### ISSUE THREAD

**Issue by AmosLucky** [wilburt/flutter_paystack#73]
@wilburt this plugin is far behind, it doesnt have the latest features like the web(javascript) plugin e.g USSD, BANK TRANSFER etc. and there was no place in the code clearly declared to show that the transaction is successfull or failed so that developer will start writing there own success or failure code from there. please if u have chance address these issues. i dont know how paystack operates i would have  contributed in that part.

**Comment by wilburt** [comment]
The plugin is highly limited in functionality because the payment methods you mentioned requires the use of a secret key on the client-side. 

For the status of a transaction, please, can you read the documentation?

**Comment by Itope84** [comment]
#63
