### ISSUE TITLE
Dark Theme - White background makes Text disappear

### ISSUE THREAD

**Issue by nuelsoft** [wilburt/flutter_paystack#75]
Running a dark theme context makes, majority of content in payout modal disappear. 
This is because, the contents adapt to the dark mode and are displayed as white, with the white background, things tend to disappear.
<img width="474" alt="Screenshot 2020-11-26 at 06 23 09" src="https://user-images.githubusercontent.com/32180049/100311359-e1435280-2faf-11eb-8c4e-9643ff1ab739.png">

**Comment by nuelsoft** [comment]
@wilburt if you'd look into this, it'll be very nice. I also have a proposed fix and have made a PR. 
Thank you

**Comment by wilburt** [comment]
I believe this has been fixed in #76
