### ISSUE TITLE
Unresolved reference: VERSION_NAME  Unresolved reference: VERSION_CODE

### ISSUE THREAD

**Issue by bartukaan** [wilburt/flutter_paystack#79]
Why I got that kind of error?

e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.4+1\android\src\main\kotlin\co\paystack\flutterpaystack\MethodCallHandlerImpl.kt: (33, 100): Unresolved reference: VERSION_NAME
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_paystack-1.0.4+1\android\src\main\kotlin\co\paystack\flutterpaystack\MethodCallHandlerImpl.kt: (43, 48): Unresolved reference: VERSION_CODE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_paystack:compileDebugKotlin'.

**Comment by timzprof** [comment]
I also have this issue

**Comment by Bharavi26** [comment]
Hello @bartukaan sir,
have you found any solution ? i am facing same issue

**Comment by bartukaan** [comment]
I've added version_name and version_code manually to get rid of the situation but I don't think this is a very healthy solution

**Comment by Bharavi26** [comment]
in which file sir ?
i tried by adding version code n name in build.gradle but facing same err

**Comment by bartukaan** [comment]
\flutter_paystack-1.0.4+1\android\src\main\kotlin\co\paystack\flutterpaystack\MethodCallHandlerImpl.kt: 

 "getUserAgent" -> {
                //result.success("Android_" + Build.VERSION.SDK_INT + "_Paystack_" + BuildConfig.VERSION_NAME)
                result.success("Android_" + "29" + "_Paystack_" + "1.0.0" )
            }

            "getVersionCode" -> {
                //result.success(BuildConfig.VERSION_CODE.toString())
                result.success("1")
            }

**Comment by bidex160** [comment]
Hi, @barkutan can find the methodcallhandlerimpl.kt

**Comment by Bharavi26** [comment]
@bidex160 sir, its under flutter sdk's folder ... hosted\pub.dartlang.org\flutter_paystack-1.0.4+1\android\src\main\kotlin\co\paystack\flutterpaystack\

**Comment by bidex160** [comment]
Ok thanks @bartukaan ...
"getUserAgent" -> {
            //result.success("Android_" + Build.VERSION.SDK_INT + "_Paystack_" + BuildConfig.VERSION_NAME)
            result.success("Android_" + "29" + "_Paystack_" + "1.0.0" )
        }

        "getVersionCode" -> {
            //result.success(BuildConfig.VERSION_CODE.toString())
            result.success("1")
        }


So I'm going to paste this right,?

**Comment by bartukaan** [comment]
@bidex160  yes, right.

**Comment by bartukaan** [comment]
Hi @wilburt , Is there any idea with that situation?

**Comment by bidex160** [comment]
@bartukaan solution was good..thanks boss

**Comment by f0rx** [comment]
> \flutter_paystack-1.0.4+1\android\src\main\kotlin\co\paystack\flutterpaystack\MethodCallHandlerImpl.kt:
> 
> ```
>         "getUserAgent" -> {
>             //result.success("Android_" + Build.VERSION.SDK_INT + "_Paystack_" + BuildConfig.VERSION_NAME)
>             result.success("Android_" + "29" + "_Paystack_" + "1.0.0" )
>         }
> 
>         "getVersionCode" -> {
>             //result.success(BuildConfig.VERSION_CODE.toString())
>             result.success("1")
>         }
> ```

Is this really a solution?? How about CI builds?

**Comment by bartukaan** [comment]
@f0rx  it is just temporary solution until development team fix it.

**Comment by wilburt** [comment]
@f0rx @bartukaan this has already been fixed and released. Please, update to `1.0.5+1`.

**Comment by f0rx** [comment]
> @f0rx @bartukaan this has already been fixed and released. Please, update to `1.0.5+1`.

Yes true. Unfortunately i'm not prepared to migrate my project to Null-safety.
Solution that worked for me was fork the repo at ^1.0.4+1, apply the fix above and depend on my fork.
Thanks for the tip 👍🏾
