### ISSUE TITLE
Why checkout require secret key ?

### ISSUE THREAD

**Issue by TarekkMA** [wilburt/flutter_paystack#8]
Putting the secret key in the client code imposes security risks. and this behavior is being recommended in the README file. Shouldn't we process the info related to the secret key in the backend?

Am I right? if so how can use the checkout process without the need for the secret key?

**Comment by wilburt** [comment]
Yes, you are very right. Putting the secret key in the client side is a big security risk and I wasn't aware of this as at when developing the plugin. Stuff pertaining to secret keys should be handled on the server side.

We should be able to use the card checkout option without the secret key by removing the transaction initialization and verification from the plugin. However, we will have to sacrifice the bank payment as this can't be done without a secret for now. 

I will push a release that will deprecate the usage of the secret key and consequently, the bank payment in the coming days.

Thanks a lot for this issue.

**Comment by TarekkMA** [comment]
@wilburt thank you a lot for this swift reply and your action 👍really appreciate it

**Comment by wilburt** [comment]
@TarekkMA  From [v0.10.0](https://github.com/wilburt/flutter_paystack/releases/tag/v0.10.0), you can use `checkout` without the need for a secret key. However, you will have to do transaction initialization and verification from your backend.
