### ISSUE TITLE
Change in Currency

### ISSUE THREAD

**Issue by TMoreMaker** [wilburt/flutter_paystack#84]
Firstly, Thank you for this amazing package!!!

Hello, I wanted to know how if there was an easy way to change the currency to ZAR and whether it will get rid of the onscreen error in the image below

![Screenshot_1608812985](https://user-images.githubusercontent.com/67902906/103088878-e61e1500-45f4-11eb-8b28-b8e2c3d91839.png)

**Comment by TMoreMaker** [comment]
I figured it out thanks 😃

**Comment by holy-dev** [comment]
@TMoreMaker dude you should always mention how you did it.

**Comment by developmentkws** [comment]
To change currency , Just use

      Charge charge = Charge()
      ..amount = (1 * 100).toInt()
      ..currency = "USD" //HERE YOU CAN PUT CURRENCY as STRING
      ..email = emailCnt.text
      ..reference = _getReference()
      ..putCustomField('UserId', userID)
      ..putCustomField('Charged From', 'test')
      ..card = _getCardFromUI();
