### ISSUE TITLE
Mobile Money feature

### ISSUE THREAD

**Issue by leadenpraise** [wilburt/flutter_paystack#87]
Paystack has updated their sdk to enable the mobile money payment. it will be nice to update this plugin to add the mobile money feature

**Comment by wilburt** [comment]
That's nice. I'll take a look to see if we can implement it here. Thanks for letting me know about this.

**Comment by leadenpraise** [comment]
nice! any news as to if it can be done?

**Comment by wilburt** [comment]
@

> Paystack has updated their sdk to enable the mobile money payment. it will be nice to update this plugin to add the mobile money feature

Which of their SDKs, please?

**Comment by leadenpraise** [comment]
Hi! These ones

https://github.com/paystackHQ/checkout-ios

https://github.com/paystackHQ/checkout-android

**Comment by wilburt** [comment]
From what I can see, the experience is not native. The experience is being handled on a WebView.

**Comment by leadenpraise** [comment]
Yeah I guess. In that case, nothing can be done in the flutter side? We are
very limited without the mobile money feature

**Comment by wilburt** [comment]
Sorry about that. You can import the iOS and Android libraries natively and use Platform Channels to call it from Flutter.
