### ISSUE TITLE
Support for Flutter 2 - (Sound Null Safety)

### ISSUE THREAD

**Issue by KgotsoK** [wilburt/flutter_paystack#88]
Hi, Please add support for the latest version of Flutter with Sound Null Safety

**Comment by KgotsoK** [comment]
@wilburt Please add me as a contributor - want to add null safety to this package

**Comment by wilburt** [comment]
@KgotsoK, thank you for wanting to contribute. Please, can you clone this repo, implement the changes in the cloned repo and make a PR to this repo when you're done?

**Comment by wilburt** [comment]
Please, remove your ssh key from here, thanks!

**Comment by KgotsoK** [comment]
Cool, will do @wilburt

**Comment by KgotsoK** [comment]
@wilburt I am not able to push a bransh on to this repo. Done with the migration. I think you need to open up access for my username.

**Comment by wilburt** [comment]
I am sorry, man. I gave you the wrong instructions. The right instructions would have been to fork the repo, clone the forked repo, make changes on the cloned repo and make a PR.

To fix the access issue. Fork this repo and then change the git URL of your local repo (the one where you implemented the changes). Push the code and make a PR.

**Comment by KgotsoK** [comment]
Okay... will do this tomorrow morning. no problem. 😄

**Comment by wilburt** [comment]
@KgotsoK  is there any update on this?

**Comment by intellect4all** [comment]
has the null safety been added? @wilburt

**Comment by wilburt** [comment]
@intellect4all  yes. Update to the latest version.

**Comment by KgotsoK** [comment]
Sorry @wilburt - had some personal things to deal with... will be sure to contribute in the future though. Thanks for handling this.

**Comment by tommygr8** [comment]
Any update on the null safety ?

**Comment by wilburt** [comment]
@tommygr8 null safety is supported now. Update to the latest version.

**Comment by intellect4all** [comment]
@wilburt Hi bro, i am having issues implementing the package in my project. Do you mind sharing me your mail so i can send more details to you. I will be very glad. Thanks
