### ISSUE TITLE
Discrepancies in test payments

### ISSUE THREAD

**Issue by lordlamee** [wilburt/flutter_paystack#89]
![Screenshot_20210309-024253](https://user-images.githubusercontent.com/57968200/110407153-b0c98500-8083-11eb-9872-d17f7c91245e.jpg)
![Screenshot_20210309-025217](https://user-images.githubusercontent.com/57968200/110407157-b1fab200-8083-11eb-940f-eb06f89e65f3.jpg)

As you can see, there is a discrepancy between the amount meant to be charged and the amount actually charged. I have no idea why this is happening.

Also, why not allow the charge amount to accept a double instead of an integer?

**Comment by KgotsoK** [comment]
Looks like an amount is being displayed in cents but sent to Paystack in Nairas. So I'm guessing you're initialising the transaction on your own backend right?

**Comment by lordlamee** [comment]
> Looks like an amount is being displayed in cents but sent to Paystack in Nairas. So I'm guessing you're initialising the transaction on your own backend right?

Yes, I am, that makes sense. how do I fix that?

**Comment by Mastersam07** [comment]
@lordlamee let me know if that fixes your issue

**Comment by lordlamee** [comment]
Thanks for your help.
