### ISSUE TITLE
class 'PaystackPlugin' doesn't have a default constructor

### ISSUE THREAD

**Issue by intellect4all** [wilburt/flutter_paystack#93]
I kept getting a `class 'PaystackPlugin' doesn't have a default constructor ` whenever i try setting an instance of the plugin as stated in your readme. Is there something i am getting wrong?

![Screenshot from 2021-03-17 16-11-48](https://user-images.githubusercontent.com/37888344/111491854-7d9a8c00-873c-11eb-8b19-20f543305c06.png)

**Comment by intellect4all** [comment]
yes. I tried another method of initializing directly, but i kept getting a public key not set or invalid.

**Comment by wilburt** [comment]
What version of the package are you using?

**Comment by intellect4all** [comment]
i didn't set a version.

`flutter_paystack:`

**Comment by wilburt** [comment]
Can you use this: flutter_paystack: ^1.0.5?

Delete **pubspec.lock** and run `flutter packages get`

**Comment by intellect4all** [comment]
Thank you. I have been able to fix it
