### ISSUE TITLE
Paystack null safety version is not initializing on flutter 2

### ISSUE THREAD

**Issue by Codesait** [wilburt/flutter_paystack#95]
E/flutter (23171): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Paystack SDK has not been initialized. The SDK has to be initialized before use
E/flutter (23171): #0      PaystackPlugin._validateSdkInitialized (package:flutter_paystack/src/common/paystack.dart:143:7)
E/flutter (23171): #1      PaystackPlugin.publicKey (package:flutter_paystack/src/common/paystack.dart:61:5)
E/flutter (23171): #2      PaystackPlugin.checkout (package:flutter_paystack/src/common/paystack.dart:130:22)
E/flutter (23171): #3      payStackPay (package:proptor/payment_methods/payStack.dart:41:44)
E/flutter (23171): #4      _PaymentMethodsState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:proptor/screens/payment_methods.dart:167:48)
E/flutter (23171): #5      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (23171): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (23171): #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:176:18)
E/flutter (23171): #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:674:39)
E/flutter (23171): #9      Future._propagateToListeners (dart:async/future_impl.dart:730:37)
E/flutter (23171): #10     Future._completeWithValue (dart:async/future_impl.dart:539:5)
E/flutter (23171): #11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
E/flutter (23171): #12     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (23171): #13     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (23171): #14     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (23171): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (23171): #16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (23171): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (23171):

**Comment by wilburt** [comment]
Hi @Codesait can you add a snippet of how you're calling the plugin? A runnable snippet will help.

**Comment by Codesait** [comment]
final plugin = PaystackPlugin();

 
  @override
  void initState() {
    plugin.initialize(publicKey: paystackTestKEy);
    super.initState();
  }

**Comment by Codesait** [comment]
> Hi @Codesait can you add a snippet of how you're calling the plugin? A runnable snippet will help.

final plugin = PaystackPlugin();

@override
void initState() {
plugin.initialize(publicKey: paystackTestKEy);
super.initState();
}

**Comment by wilburt** [comment]
@Codesait can you add a full widget that I can run? Also, include the part where you call the plugin to make payment.

**Comment by Anyitechs** [comment]
@wilburt I have the same error too!

**Comment by wilburt** [comment]
@Anyitechs can you add a runnable snippet of how you're calling the plugin?

**Comment by Anyitechs** [comment]
@wilburt Okay, give me a second.

**Comment by Anyitechs** [comment]
`
import 'package:flutter_paystack/flutter_paystack.dart';

...........///

final GlobalKey<ScaffoldState> scaffoldKey = new GlobalKey<ScaffoldState>();

  @override
  void initState() {
    PaystackPlugin.initialize(publicKey: publicKey);
    super.initState();
  }

  String _getReference() {
    String platform;
    if (Platform.isIOS) {
      platform = 'iOS';
    } else {
      platform = 'Android';
    }
    return 'ChargedFrom${platform}_${DateTime.now().millisecondsSinceEpoch}';
  }

  ///paystack payment
  chargeCard() async {
    setState(() {
      isGeneratingCode = !isGeneratingCode;
    });
    // controller2.setState(() {});

    Map accessCode = await createAccessCode(
        "[Secret key here]",
        (100 * 100).toInt(),
        'test@test.com',
        _getReference());
    print(accessCode);

    setState(() {
      isGeneratingCode = !isGeneratingCode;
    });
    // controller2.setState(() {});

    // _closeBottomSheet2();

    Charge charge = Charge()
      ..amount = (100 * 100).toInt()
      ..reference = _getReference()
      ..accessCode = accessCode["data"]["access_code"]
      ..email = 'test@test.com';
    CheckoutResponse response = await PaystackPlugin.checkout(
      context,
      logo: Image(image: AssetImage(imageHere),),
      method: CheckoutMethod.selectable,
//      _method, // Defaults to CheckoutMethod.selectable
      charge: charge,
    );
    if (response.status == true) {
      print('Ref =' + response.reference.toString());
      print('Checking Transaction Status');
      setState(() {
        isLoading = true;
      });
      try {
        var respons = await Network()
            .getPayStack(response.reference.toString())
            .timeout(const Duration(seconds: 10));
        print("*******printing reference");
        print(response.reference);
        print(respons);
        print(respons.reasonPhrase);
        print(respons.statusCode);

        if (respons.statusCode == 200) {
          print('Success');
          // _upload();
          //todo handle payment file upload here
          // _detailsUpload();
        } else {
          setState(() {
            isLoading = false;
          });
          _showAlertDialogue();
          print(respons.stream);
        }
      } on TimeoutException catch (_) {
        print('timeout  exception occured' + _.toString());
        setState(() {
          isLoading = false;
        });
        _showMsg(_.message);
      } on SocketException catch (_) {
        print('Socket exception occured' + _.toString());
        setState(() {
          isLoading = false;
        });
        _showMsg(_.message);
      } on Exception catch (_) {
        setState(() {
          isLoading = false;
        });
        _showMsg(_.toString());
        print(_);
      }
    } else {
      setState(() {
        isGeneratingCode = isGeneratingCode;
      });
      // controller2.setState(() {});
      Fluttertoast.showToast(msg: response.message);
    }
  }

  _showMsg(msg) {
    final snackBar = SnackBar(
      content: Text(msg),
      action: SnackBarAction(
        label: 'Close',
        onPressed: () {
          // Some code to undo the change!
        },
      ),
    );
    FocusScope.of(context).requestFocus(new FocusNode());
    scaffoldKey.currentState?.removeCurrentSnackBar();
    scaffoldKey.currentState.showSnackBar(snackBar);
  }


_showAlertDialogue() {
    showDialog(
        context: context,
        builder: (context) {
          return SimpleDialog(
            contentPadding: EdgeInsets.symmetric(horizontal: 15),
            titlePadding: EdgeInsets.symmetric(horizontal: 15, vertical: 20),
            title: ListTile(
              contentPadding: EdgeInsets.symmetric(horizontal: 0),
//                    leading: Icon(Icons.bubble_chart, color:  Colors.black,),
              title: Text('Something went wrong. ',
                  maxLines: 2,
                  style: TextStyle(fontWeight: FontWeight.w800, fontSize: 15)),
              subtitle: Text('Don\'t panic, we\' ve got u covered'),
//          trailing: Text('Step 2/3', style: TextStyle(color: Colors.green, fontSize: 10),),
            ),
            children: [
              Text(
                'Seems an error occurred while trying to process your transaction.'
              ),
              SizedBox(
                height: 20,
              )
            ],
          );
        });
    setState(() {
      isLoading = false;
    });
  }




  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      /.........../

   GestureDetector(
                onTap: () => { chargeCard() },
                child: Container(
                  margin: EdgeInsets.only(top: 35.0),
                  width: 335.0,
                  height: 45.0,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(5.0),
                    color: Color.fromRGBO(238, 238, 238, 0.8)
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Image(
                        image: AssetImage('images/paystack_logo.png'),
                      ),
                      SizedBox(
                        width: 25.0,
                      ),
                      isGeneratingCode ? CircularProgressIndicator(
                        value: 1.0,
                      ) :
                      Text(
                        'Paystack',
                        style: TextStyle(
                            fontSize: 14.0,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            color: Color(0xff333333)
                        ),
                      )
                    ],
                  ),
                ),
              ),
`

**Comment by Anyitechs** [comment]
`import 'package:flutter_paystack/flutter_paystack.dart';

...........///

final GlobalKey scaffoldKey = new GlobalKey();

@override
void initState() {
PaystackPlugin.initialize(publicKey: publicKey);
super.initState();
}

String getReference() {
String platform;
if (Platform.isIOS) {
platform = 'iOS';
} else {
platform = 'Android';
}
return 'ChargedFrom${platform}${DateTime.now().millisecondsSinceEpoch}';
}

///paystack payment
chargeCard() async {
setState(() {
isGeneratingCode = !isGeneratingCode;
});
// controller2.setState(() {});

Map accessCode = await createAccessCode(
    "[Secret key here]",
    (100 * 100).toInt(),
    'test@test.com',
    _getReference());
print(accessCode);

setState(() {
  isGeneratingCode = !isGeneratingCode;
});
// controller2.setState(() {});

// _closeBottomSheet2();

Charge charge = Charge()
  ..amount = (100 * 100).toInt()
  ..reference = _getReference()
  ..accessCode = accessCode["data"]["access_code"]
  ..email = 'test@test.com';
CheckoutResponse response = await PaystackPlugin.checkout(
  context,
  logo: Image(image: AssetImage(imageHere),),
  method: CheckoutMethod.selectable,
// _method, // Defaults to CheckoutMethod.selectable
charge: charge,
);
if (response.status == true) {
print('Ref =' + response.reference.toString());
print('Checking Transaction Status');
setState(() {
isLoading = true;
});
try {
var respons = await Network()
.getPayStack(response.reference.toString())
.timeout(const Duration(seconds: 10));

    if (respons.statusCode == 200) {
      print('Success');
      // _upload();
      //todo handle payment file upload here
      // _detailsUpload();
    } else {
      setState(() {
        isLoading = false;
      });
      _showAlertDialogue();
      print(respons.stream);
    }
  } on TimeoutException catch (_) {
    print('timeout  exception occured' + _.toString());
    setState(() {
      isLoading = false;
    });
    print(_.message);
  } on SocketException catch (_) {
    print('Socket exception occured' + _.toString());
    setState(() {
      isLoading = false;
    });
    print(_.message);
  } on Exception catch (_) {
    setState(() {
      isLoading = false;
    });
    print(_.toString());
  }
} else {
  setState(() {
    isGeneratingCode = isGeneratingCode;
  });
  // controller2.setState(() {});
  Fluttertoast.showToast(msg: response.message);
}
}

@override
Widget build(BuildContext context) {
return Scaffold(
key: scaffoldKey,
/.........../

GestureDetector(
onTap: () => { chargeCard() },
child: Container(
margin: EdgeInsets.only(top: 35.0),
width: 335.0,
height: 45.0,
decoration: BoxDecoration(
borderRadius: BorderRadius.circular(5.0),
color: Color.fromRGBO(238, 238, 238, 0.8)
),
child: Row(
mainAxisAlignment: MainAxisAlignment.center,
children: [
Image(image: AssetImage('images/paystack_logo.png'),),
SizedBox(width: 25.0,),
isGeneratingCode ? CircularProgressIndicator(value: 1.0,) :
Text(
'Paystack',
style: TextStyle(
fontSize: 14.0,
fontFamily: 'Poppins',
fontWeight: FontWeight.w500,
color: Color(0xff333333)),)],),),),`

**Comment by Anyitechs** [comment]
@wilburt Please note that I'm using the `"1.0.4+1"` version here, because the latest version is conflicting with the `rave_flutter ` SDK you built too. I need the two payment integration on the app I'm working on so I'm using the two SDKs. The latest version of `flutter_paystack` worked fine with flutter 2, but I keep getting this error when I switched to this version `"1.0.4+1"`. 

It will be nice if you can update the `rave_flutter` SDK as so many of it's packages are no longer compatible with flutter 2. I had to upgrade the `flutter_svg` dependency version on my local copy of the SDK to get it to work even after I've downgraded some of my packages. It will be nice if you can look at that too. Thanks.

**Comment by wilburt** [comment]
@Anyitechs  I will advise you to bump flutter_paystack  to the latest version and override the troublesome dependency as I am waiting on johnpryan/tripledes-dart#14 to support Flutter 2 for rave_flutter.

**Comment by benjaminudoh10** [comment]
I had to look deep into the package code before I concluded that the error was not from the package.

What worked for me is to put an `await` before the `plugin.initialize(...)`.

@Codesait
```
final plugin = PaystackPlugin();

@override
void initState() async {
  await plugin.initialize(publicKey: paystackTestKEy);
  super.initState();
}
```

**Comment by DEVSOG12** [comment]
@benjaminudoh10  It is not possible to await in `initState() ` it should be asynchronous. Having `await` means that the Widget Build is delayed.

I tried this and it worked: 


    final plugin = PaystackPlugin();
    
    @override
    void initState()  {
       plugin.initialize(publicKey: paystackkey);
      super.initState();
    }

Make sure you always call the same instance of the plugin. 


Incase you need to run an await in the `initState()` you can create an async function and run the function.

**Comment by Ruqoyah549** [comment]
Still getting the same error even after this

final plugin = PaystackPlugin();

@override
void initState()  {
   plugin.initialize(publicKey: paystackkey);
  super.initState();
<img width="1030" alt="Screenshot 2021-12-18 at 10 07 02" src="https://user-images.githubusercontent.com/34499639/146635823-aea4df2f-805f-4ff3-8c9d-465be105300d.png">
}

**Comment by wilburt** [comment]
This has been fixed. Update to the latest version and reopen this issue if the problem persists.
