### ISSUE TITLE
Bank Accounts are limited

### ISSUE THREAD

**Issue by Mind-Reaper** [wilburt/flutter_paystack#97]
Paying with Bank CheckoutMethod brings a list of just 4 banks. Is that a bug are those the only accounts Paystack is accepting?

![Simulator Screen Shot - lanre's iPhone - 2021-04-26 at 17 48 30](https://user-images.githubusercontent.com/66218434/116120643-a9078380-a6b7-11eb-89ba-18124dcdf175.png)

**Comment by wilburt** [comment]
This is from Paystack, please. Check [the Paystack demo](https://paystack.com/demo) to confirm.
