### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getDeviceId on channel plugins.wilburt/flutter_paystack)

### ISSUE THREAD

**Issue by carlomigueldy** [wilburt/flutter_paystack#98]
![image](https://user-images.githubusercontent.com/45052332/116844165-dfdc1d00-ac14-11eb-8e8d-a0dce819e4a8.png)

Not sure why I am receiving this error every time I initialize the plugin.

What am I missing?

**Comment by wilburt** [comment]
Hello @carlomigueldy, have you tried doing a fresh build and installation of the app?

**Comment by carlomigueldy** [comment]
Have not done that yet. Will do that now

**Comment by carlomigueldy** [comment]
@wilburt I did that and it worked. Thanks man!

**Comment by DavidJoanes** [comment]
@wilburt Hey Wil, great job so far. Please, I keep getting an error whenever I click on the button that calls the payment function which I created. 
![Capture](https://user-images.githubusercontent.com/63173423/172312852-2e642938-a63f-4476-b0a2-7ca906d5be36.PNG)

**Comment by MonspeetTech** [comment]
@wilburt hello, i am having this same error despite rebuilding the app multiple times.. any idea?

**Comment by MonspeetTech** [comment]
> @wilburt Hey Wil, great job so far. Please, I keep getting an error whenever I click on the button that calls the payment function which I created. I have done everything I can, including a fresh build, flutter clean, etc. By the way, I'm working on a windows application. ![Capture](https://user-images.githubusercontent.com/63173423/172312852-2e642938-a63f-4476-b0a2-7ca906d5be36.PNG)
